/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "src/ma_msg.pb-c.h"
void   plan_multi_agent_msg_path_operator__init
                     (PlanMultiAgentMsgPathOperator         *message)
{
  static PlanMultiAgentMsgPathOperator init_value = PLAN_MULTI_AGENT_MSG_PATH_OPERATOR__INIT;
  *message = init_value;
}
size_t plan_multi_agent_msg_path_operator__get_packed_size
                     (const PlanMultiAgentMsgPathOperator *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plan_multi_agent_msg_path_operator__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plan_multi_agent_msg_path_operator__pack
                     (const PlanMultiAgentMsgPathOperator *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plan_multi_agent_msg_path_operator__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plan_multi_agent_msg_path_operator__pack_to_buffer
                     (const PlanMultiAgentMsgPathOperator *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plan_multi_agent_msg_path_operator__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlanMultiAgentMsgPathOperator *
       plan_multi_agent_msg_path_operator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlanMultiAgentMsgPathOperator *)
     protobuf_c_message_unpack (&plan_multi_agent_msg_path_operator__descriptor,
                                allocator, len, data);
}
void   plan_multi_agent_msg_path_operator__free_unpacked
                     (PlanMultiAgentMsgPathOperator *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plan_multi_agent_msg_path_operator__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plan_multi_agent_msg__init
                     (PlanMultiAgentMsg         *message)
{
  static PlanMultiAgentMsg init_value = PLAN_MULTI_AGENT_MSG__INIT;
  *message = init_value;
}
size_t plan_multi_agent_msg__get_packed_size
                     (const PlanMultiAgentMsg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plan_multi_agent_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plan_multi_agent_msg__pack
                     (const PlanMultiAgentMsg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plan_multi_agent_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plan_multi_agent_msg__pack_to_buffer
                     (const PlanMultiAgentMsg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plan_multi_agent_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlanMultiAgentMsg *
       plan_multi_agent_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlanMultiAgentMsg *)
     protobuf_c_message_unpack (&plan_multi_agent_msg__descriptor,
                                allocator, len, data);
}
void   plan_multi_agent_msg__free_unpacked
                     (PlanMultiAgentMsg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plan_multi_agent_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor plan_multi_agent_msg_path_operator__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsgPathOperator, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cost",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsgPathOperator, cost),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plan_multi_agent_msg_path_operator__field_indices_by_name[] = {
  1,   /* field[1] = cost */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange plan_multi_agent_msg_path_operator__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plan_multi_agent_msg_path_operator__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PlanMultiAgentMsgPathOperator",
  "PlanMultiAgentMsgPathOperator",
  "PlanMultiAgentMsgPathOperator",
  "",
  sizeof(PlanMultiAgentMsgPathOperator),
  2,
  plan_multi_agent_msg_path_operator__field_descriptors,
  plan_multi_agent_msg_path_operator__field_indices_by_name,
  1,  plan_multi_agent_msg_path_operator__number_ranges,
  (ProtobufCMessageInit) plan_multi_agent_msg_path_operator__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue plan_multi_agent_msg__type__enum_values_by_number[7] =
{
  { "TERMINATE", "PLAN_MULTI_AGENT_MSG__TYPE__TERMINATE", 1 },
  { "PUBLIC_STATE", "PLAN_MULTI_AGENT_MSG__TYPE__PUBLIC_STATE", 2 },
  { "TRACE_PATH", "PLAN_MULTI_AGENT_MSG__TYPE__TRACE_PATH", 3 },
  { "TRACE_PATH_DONE", "PLAN_MULTI_AGENT_MSG__TYPE__TRACE_PATH_DONE", 4 },
  { "_TERMINATE", "PLAN_MULTI_AGENT_MSG__TYPE___TERMINATE", 256 },
  { "_TERMINATE_REQUEST", "PLAN_MULTI_AGENT_MSG__TYPE___TERMINATE_REQUEST", 257 },
  { "_TERMINATE_ACK", "PLAN_MULTI_AGENT_MSG__TYPE___TERMINATE_ACK", 258 },
};
static const ProtobufCIntRange plan_multi_agent_msg__type__value_ranges[] = {
{1, 0},{256, 4},{0, 7}
};
const ProtobufCEnumValueIndex plan_multi_agent_msg__type__enum_values_by_name[7] =
{
  { "PUBLIC_STATE", 1 },
  { "TERMINATE", 0 },
  { "TRACE_PATH", 2 },
  { "TRACE_PATH_DONE", 3 },
  { "_TERMINATE", 4 },
  { "_TERMINATE_ACK", 6 },
  { "_TERMINATE_REQUEST", 5 },
};
const ProtobufCEnumDescriptor plan_multi_agent_msg__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "PlanMultiAgentMsg.Type",
  "Type",
  "PlanMultiAgentMsg__Type",
  "",
  7,
  plan_multi_agent_msg__type__enum_values_by_number,
  7,
  plan_multi_agent_msg__type__enum_values_by_name,
  2,
  plan_multi_agent_msg__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plan_multi_agent_msg__field_descriptors[10] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, type),
    &plan_multi_agent_msg__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "agent_name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, agent_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, has_state),
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cost",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, has_cost),
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, cost),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "real_cost",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, has_real_cost),
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, real_cost),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heuristic",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, has_heuristic),
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, heuristic),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "init_state",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, has_init_state),
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, init_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    21,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, n_path),
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, path),
    &plan_multi_agent_msg_path_operator__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path_first_state",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, has_path_first_state),
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, path_first_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trace_path_initiator",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlanMultiAgentMsg, trace_path_initiator),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plan_multi_agent_msg__field_indices_by_name[] = {
  1,   /* field[1] = agent_name */
  3,   /* field[3] = cost */
  5,   /* field[5] = heuristic */
  6,   /* field[6] = init_state */
  7,   /* field[7] = path */
  8,   /* field[8] = path_first_state */
  4,   /* field[4] = real_cost */
  2,   /* field[2] = state */
  9,   /* field[9] = trace_path_initiator */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange plan_multi_agent_msg__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 10, 2 },
  { 20, 6 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor plan_multi_agent_msg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PlanMultiAgentMsg",
  "PlanMultiAgentMsg",
  "PlanMultiAgentMsg",
  "",
  sizeof(PlanMultiAgentMsg),
  10,
  plan_multi_agent_msg__field_descriptors,
  plan_multi_agent_msg__field_indices_by_name,
  3,  plan_multi_agent_msg__number_ranges,
  (ProtobufCMessageInit) plan_multi_agent_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
